#pragma once

#include "alias.cpp"
#include "base.cpp"
#include "concepts.cpp"
#include "container.cpp"
#include "deb.cpp"
#include "input.cpp"
#include "ds/all.cpp"
#include "math.cpp"
#include "misc.cpp"
#include "modint.cpp"
#include "output.cpp"
#include "views.cpp"
#include "wrapper.h"
