#!/usr/bin/env bash
set -e
tail -n +2 < compile_flags_prod.txt | xargs /opt/homebrew/opt/llvm/bin/clang++ main.cpp -o build/main
tail -n +2 < compile_flags_prod.txt | xargs /opt/homebrew/opt/llvm/bin/clang++ gen.cpp -o build/gen
#
# Create named pipes

# Run command1 in the background, redirecting its output to pipe1
# build/gen 5 < pipe1 | build/main > pipe1

# # Run command2, redirecting its input from pipe1 and output to pipe2
# build/main < pipe2 > pipe1

# # Read the output of command2 from pipe2
# cat pipe1
# cat pipe2

# # Clean up named pipes

echo "Running tests..."
echo ""
for((i = 1; ; ++i)); do
      rm -f pipe1 pipe2
      mkfifo pipe1 pipe2
      build/main > pipe1 < pipe2 &
      build/gen $i < pipe1 > pipe2 || break
    echo -e "\e[1APassed test: "  $i
done
# echo "WA on the following test:"
# cat input_file
# echo "Your answer is:"
# cat myAnswer
# echo "Correct answer is:"
# cat correctAnswer
