#!/usr/bin/env bash
set -e
tail -n +2 < compile_flags_prod.txt | xargs /opt/homebrew/opt/llvm/bin/clang++ template.cpp -DENTRY=main -o build/main || exit
tail -n +2 < compile_flags_prod.txt | xargs /opt/homebrew/opt/llvm/bin/clang++ template.cpp -DENTRY=gen -o build/gen || exit
tail -n +2 < compile_flags_prod.txt | xargs /opt/homebrew/opt/llvm/bin/clang++ template.cpp -DENTRY=validate -o build/validate || exit

echo "Running tests..."
echo ""
for((i = 1; ; ++i)); do
    build/gen $i > build/input_file
    build/main < build/input_file > build/myAnswer 2> /dev/null
    cat build/input_file build/myAnswer > build/val_check
    rm -f build/val_error
    build/validate <build/val_check &>> build/val_error || break
    echo -e "\e[1APassed test: "  $i
done
cp build/input_file input_file
echo "WA on the following test:"
cat build/input_file
echo "Your answer is:"
cat build/myAnswer
echo "Validation assertion"
cat build/val_error
