#!/usr/bin/env bash

tail -n +2 < compile_flags_deb.txt | xargs /opt/homebrew/opt/llvm/bin/clang++ template.cpp -o build/tests -DENTRY=testing/tests || exit

build/tests --no-intro=true < testing/test_input.txt
